package tech.ada.extends_insights.domain.enums;

public enum Category {
    SOFTWARE_DEVELOPMENT,
    INFRASTRUCTURE_AND_NETWORKS,
    AI_AND_MACHINE_LEARNING,
    CYBERSECURITY,
    DATA_SCIENCE_AND_BIG_DATA,
    WEB_TECHNOLOGIES,
    OPERATING_SYSTEM
}
